baseurl = "https://www.atharva.io"
title = "wiredhikari"
theme = "hugo"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "wiredhikari"
  info = "Just another open source fanboy and web3 researcher"
  description = "hikari's warehouse"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "atharvaamritkar@protonmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/wiredhikari/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/wiredhikari/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/wired_hikari/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 4
  url = "https://twitter.com/wired_hikari/"
[[params.social]]
  name = "Gmail"
  icon = "fa fa-envelope fa-2x"
  weight = 5
  url = "https://twitter.com/wired_hikari/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

[[menu.main]]
  name = "Tags"
  weight = 3
  url = "tags/"
  
[[menu.main]]
  name = "Projects"
  weight = 4
  url = "projects/"

[[menu.main]]
  name = "Contact Me"
  weight = 5
  url = "contact/"

  